CREATE TABLE T_EWA_USUARIO (
id_usuario NUMERIC(10) PRIMARY KEY,
nm_usuario VARCHAR2(100),
email VARCHAR2(100),
dist_km NUMERIC(10,2)
);
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE T_EWA_REGISTRO (
id_registro NUMERIC(10) PRIMARY KEY,
dt_trabalho DATE,
horas NUMERIC(2),
co2_poupado NUMERIC(10,2),
id_usuario NUMERIC(10),
CONSTRAINT FK_USUARIO FOREIGN KEY (id_usuario) REFERENCES T_EWA_USUARIO(id_usuario)
);
CREATE SEQUENCE SEQ_REGISTRO START WITH 1 INCREMENT BY 1;